travis:
  secure:
    BINSTAR_TOKEN: GEfvw13bGShiwWrJpA0VjoxThLie5gUiPwTT3TyPdrtVvct7m39qBepVOB3Aar3TbM9C50BfoU/kfXWCFmJOti1wxff+4dwPefQb5+l5mVFTw0S/+FpfthxB2/VflwmxSlDRWWh6QxF+uADOUU6kzMlcPfcYD8WFciuzqt4cE261o8mx7upV+nhzh5fCEl/SdAqu1GazuAQW4m4pqab/aJFlPCB2iUfIPUIXpAPDMWV8U3/jXMZLwm42njPJsbrUDy5Zxnl2C6tJqIkZvcJeCkYCxpPvVyq0EdVvrxqQbfz1bfpsb8ZCi8dD7XyMwOt3wPyIJJV1pkvcb1NC6qOEKzvmOzQ4atGta4FlCOnoiRihqZHrwo8NJv74YP50SoD3D7emxr0TNVfLnQVevAjoTfjp8p45hy8hxTNYLJ39DHdOZXDjSDUN5VwHvwAl9kFiQtnmNMJMERLnCvfqjHiSvgaOgzVr8ZNYDoljYa24uBBG5xpTWjFy83LN3qqxkq8O10jtOMEVfWShBCYnY9OeHpOCNJiP9Pn9LoPHVWQ+zE1ZCfUyI1hoIkliyO0L2Ov8tTlyyWGO/Aoigw2aX7ZFO9JoM+wjZjDrrMv0t9xCD0RZHC8sIShNGndTbSW4iXfdySfZ6fDnguj0vCqZXuYrr7jIWEIDNVlBcqeV4QWqtqs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
