travis:
  secure:
    BINSTAR_TOKEN: PiJaCWwaGSq7qzC3nXS/6c4mpAuCWMQSZKxD5KTgHz/uHEk5OtyWb5k4xmdBAag8YWaNUxCYIfpLo9va8opCeMXSYJtRR03GUOfgxy9CQGeWIwhRyEKW7B1kL//HBS0CvFFG/GLcDEnoEFFJBQ9rXQXZh5UI05bam9plEuvxFqHweGYrwEw8wQP1c+9CTG/ArDBwOMWAWeDzin20UyGAkw72GRLc8Eb8uuT1hbUJ80tEp4HyOQ5VHjpE97Ev42j7gfSBBN4mT7K7ycaqcc4cT52T7y2FzRWbXUWurWoWw71U9/bNLCZbAu7tM31OVkh6O22t+veNYTsjt3EAWgqxHMERxKAwBA+SgTSIJtKuQyoAZ8tNnzLGUJFYzAdAUWwtoSHe3AxXueEbcsRB+NSS13GGp/SHngex68k5o6xZYhHerYiVGSIfDZFEXP7WsBS70YTzU1jSuMXzKD9FtD4D+439L4yccYhwXQFxN7f7vEyVGuuTKVLHLMkK90q85CjtvH74rz0rs7J+W9HVQbnKnPRHr0Ni6EqQBTkuqm8oyJH99XCcxFNPr/b2BzjKNyULUs1sI9VlDGwhJm/UkvIMBGxOqkFZDjSZw2PCF3YWI00ivn57FERhCSqJM7mgFH77Ih2oIaaQHkRv+1yd0Yp2Rj2o5/orlGrSzKc+qY4fhw8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
